trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: Packaging_Credentials_Group
  
  - name: imageName
    value: abatplus/vswap
    
  - name: serviceName
    value: vswap-webview
  - name: tag
    value: '$(serviceName)-$(Build.SourceBranchName)-0.0.5'
  - name: dockerFile
    value: "./Dockerfile"
  - name: buildContext
    value: "./."

steps:
  - task: Docker@2
    displayName: "Docker Build"
    inputs:
      command: "build"
      Dockerfile: $(dockerFile)
      buildContext: $(buildContext)
     # arguments: '--build-arg NPM_TOKEN=$(NPM_TOKEN) --build-arg FONT_AWESOME_TOKEN=$(FONT_AWESOME_TOKEN)'
      repository: $(imageName)
      tags: $(tag)

  - task: Docker@2
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: "Docker Push"
    inputs:
      containerRegistry: 'DockerHub'
      repository: $(imageName)
      command: 'push'
      tags: $(tag)